### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by zbt78** [201220014/WhaleMarket-Framework#7]
你好，请问如何在虚拟机里运行这个项目啊？

**Comment by 201220014** [comment]
视频教程：https://www.bilibili.com/video/BV1k44y1s7TS
需要的环境：Linux + GCC + Make
运行步骤：
```shell
cd  path # 进入项目所在工作目录
make # 构建项目
./main # 运行项目
```

**Comment by zbt78** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "201220014/WhaleMarket-Framework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月22日(星期二) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [201220014/WhaleMarket-Framework] 问题 (Issue #7)





 
视频教程：https://www.bilibili.com/video/BV1k44y1s7TS
 需要的环境：Linux + GCC + Make
 运行步骤：
 cd  path # 进入项目所在工作目录 make # 构建项目 ./main # 运行项目
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
