### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by geoyee** [201220014/WhaleMarket-Framework#8]
你好，我发现在文档中有一处有一点问题。[https://cui-jiacai.gitbook.io/whale-market/zui-hou-yi-zuo-da-shan-jie-mian](https://cui-jiacai.gitbook.io/whale-market/zui-hou-yi-zuo-da-shan-jie-mian)

![image](https://user-images.githubusercontent.com/71769312/196603004-a7650c52-a363-46ff-9dad-e5e0f86ecb6e.png)

**Comment by geoyee** [comment]
同时在文档中没有发现关于
``` c
#define ADMIN_NAME  ...
#define ADMIN_PASS  ...
```
的表述，刚开始有点困惑`ADMIN_NAME`这在哪儿，后来在[WhaleMarket](https://github.com/201220014/WhaleMarket)这个repo的代码中看到在`config.h`下。

**Comment by JacyCui** [comment]
> 你好，我发现在文档中有一处有一点问题。https://cui-jiacai.gitbook.io/whale-market/zui-hou-yi-zuo-da-shan-jie-mian
> 
> ![image](https://user-images.githubusercontent.com/71769312/196603004-a7650c52-a363-46ff-9dad-e5e0f86ecb6e.png)

谢谢，这个地方我敲错了，我之后去改一下
